### ISSUE TITLE
INN and SNILS is null

### ISSUE THREAD

**Issue by 4n70w4** [avkluchko/x509-bundle#1]
Hi! Thanks for package. I have problem: `INN` and `SNILS` is null.

But in raw `openssl_x509_read` output `INN` and `SNILS` presented as oids.

```
  'subject' =>
    'undefined' =>
    array(3) {
      [0] =>
      string(12) "07400321373"
      [1] =>
      string(11) "74501013038"
      [2] =>
      string(13) "4791197703363"
    }
```

In `phpseclib` output `INN` and `SNILS` also presented:

```
                            [1] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => 1.2.643.3.131.1.1
                                            [value] => Array
                                                (
                                                    [numericString] => 07400321373
                                                )

                                        )

                                )

                            [2] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => 1.2.643.100.3
                                            [value] => Array
                                                (
                                                    [numericString] => 74501013038
                                                )

                                        )

                                )

                            [3] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => 1.2.643.100.1
                                            [value] => Array
                                                (
                                                    [numericString] => 4791197703363
                                                )

                                        )

                                )
```

**Comment by avkluchko** [comment]
Hi! Thank you for using this package. When I developed it, I only tested it on the certificates I had available. But, as far as I know, there can be quite a lot of options for describing the certificate subject. I take it to work. Thanks!

**Comment by avkluchko** [comment]
I think I fixed it. Can you check this?

**Comment by 4n70w4** [comment]
`INN` still is null. May be because leading zeros may be added for fill 12 chars.
But some `inn` may correctly start from zero. Example: 0103008227

May be better read OIDS instead guess key name by content.

https://2410000.ru/p_45_obektnyj_identifikator_oid.html

https://www.nalog.ru/html/docs/proj_treb121112.doc page 4


Also `SNILS` still is null. May be because leading zeros may be added.

**Comment by 4n70w4** [comment]
In `rnix/php-fpm-gost` docker image `INN`, `OGRN` and `SNILS` presented in raw `openssl_x509_parse()`.

**Comment by avkluchko** [comment]
> 
> 
> In `rnix/php-fpm-gost` docker image `INN`, `OGRN` and `SNILS` parsed out of the box.

I think it depends on the OpenSSL version. I'm testing on OpenSSL versions 1.1 and 1.0, and everything works

**Comment by 4n70w4** [comment]
I update comment https://github.com/avkluchko/x509-bundle/issues/1#issuecomment-682518640 to clear up the ambiguity.

**Comment by avkluchko** [comment]
I tried the package work with my certificates (old and new) in rnix/php-fpm-ghost, the values of INN, OGRN and SNILS are returned correctly. You do not return INN AND SNILS for all certificates?

**Comment by avkluchko** [comment]
> `INN` still is null. May be because leading zeros may be added for fill 12 chars.
> But some `inn` may correctly start from zero. Example: 0103008227

I changed package  avkluchko/government-bundle for working with short INN. To try this you need to update composer dependencies.

**Comment by avkluchko** [comment]
I found and fixed an incorrect calculation of the SNILS checksum in another my package. In addition, I checked this package with openssl 1.0.2, the information received is correct for my certificates. If you still don't work correctly, let's look specifically at your certificates?
